[workspace]
members = ["crates/*"]
resolver="2"
exclude = ["crates/gui/exports_macro"]

# [patch.crates-io]
[patch.crates-io]
probabilistic-collections = { git = "https://github.com/GaiaWorld/pi_probabilistic_collections.git" }
# tracing-chrome = { path = "../tracing-chrome" }
# bevy = { path = "../bevy" }
# pi_flex_layout = { path = "../pi_flex_layout" }
# pi_slotmap = { path = "../pi_slotmap" }

# [profile.release]
# debug=true


# [patch."https://github.com/GaiaWorld/pi_ui_render"]
# pi_ui_render = { path = "../pi_ui_render_new" }

# [patch."https://github.com/GaiaWorld/pi_hal"]
# pi_hal = { path = "../pi_hal" }

# [patch."https://github.com/GaiaWorld/pi_render"]
# pi_render = { path = "../pi_render_bevy_shader" }
# render_derive = {path = "../pi_render_bevy_shader/crates/render_derive"}

# [patch."https://github.com/GaiaWorld/pi_render_bevy"]
# pi_bevy_post_process= { path = "../pi_render_bevy/crates/post_process" }
# pi_bevy_ecs_extend = { path = "../pi_render_bevy/crates/ecs_extend" }
# pi_bevy_render_plugin = { path = "../pi_render_bevy/crates/render" }
# pi_bevy_asset = { path = "../pi_render_bevy/crates/asset" }
# pi_bevy_winit_window = { path = "../pi_render_bevy/crates/winit_window" } 
# [patch."https://github.com/GaiaWorld/pi_spatialtree"]
# pi_spatialtree ={path="../pi_spatialtree"}

# [net]
# git-fetch-with-cli = true
# offline = true
