use crate::{animation::{EAmountMode, EAnimationGroupListen, EAnimeCurve, EAnimePropertyID, EFillMode, ELoopMode}, mesh::{GeometryMeta, VInstanceAttributes}, node_materials::{MaterialUniformDefines, NodeMaterialBlock, NodematerialIncludes, P3DShaderVaryings}};
use pi_atom::Atom;
use pi_scene_context::prelude::SpriteFrame;
use serde::{Serialize, Deserialize};
use pi_export_base::export::Engine;

#[derive(Default)]
pub(crate) enum ERecordMode {
    #[default]
    None,
    Record,
    Replay,
}

#[derive(Serialize, Deserialize)]
pub(crate) enum ERecordCMD {
    ENTITY(f64)                        ,
    DISPOSE(f64)                       ,
    SCENE_DISPOSE(f64)                 ,
    LIGHTING_SHADOW_LIMIT(f64,f64,f64,f64,f64,f64,f64,f64)         ,
    RENDER_GRAPHIC(f64,f64,bool)                ,
    ENGINE_STATE(f64)                  ,
    ENGINE_DEBUG(bool)                  ,
    CREATE_GLTF_LOAD(f64, Atom, String)              ,
    CREATE_IMAGE_LOAD(Atom, bool, bool, f64)             ,
    CREATE_RENDER_TARGET(f64,f64,f64,f64,f64,f64,f64)          ,
    DISPOSE_RENDER_TARGET(f64)         ,
    SCENE(f64, u8, u8, [i32; 9])                         ,
    SCENE_ANIMATION_ENABLR(f64, bool)        ,
    SCENE_TIME(f64, f64)                    ,
    SCENE_FOGCOLOR(f64, f64, f64, f64)                ,
    SCENE_FOGPARAM(f64, f64, f64, f64, f64)                ,
    SCENE_AMBIENTCOLOR(f64, f64, f64, f64)            ,
    SCENE_AMBIENTINTENSITY(f64, f64)        ,
    LAYERMASK(f64, f64)                     ,
    SCENE_BRDF_TEXTURE(f64, Atom, bool)            ,
    SCENE_ENV_TEXTURE(f64, Atom, bool)             ,
    SCENE_SHADOWMAP(f64, Option<f64>)               ,
    SCENE_BOUNDINGBOX(f64, bool, f64)             ,
    COLLIDER(f64,f64,f64,f64,f64,f64,f64,f64, Option<f64>)                      ,
    CREATE_PICKINGRAY()             ,
    SCENE_PICK()                    ,
    ANIMATION_GROUP(f64, f64)               ,
    ANIMATION_CURVE_ID()            ,
    ANIMATION_GROUP_WEIGHT(f64, f64)        ,
    ANIMATION_GROUP_TARGET_RESET(f64)  ,
    ANIMATION_GROUP_START(f64, f64, ELoopMode, Option<f64>, f64, f64, f64, EAmountMode, f64, EFillMode, f64, f64, f64, f64)         ,
    ANIMATION_GROUP_PAUSE(f64)         ,
    ANIMATION_GROUP_STOP(f64)          ,
    ANIMATION_GROUP_GOTO(f64, f64)          ,
    ANIMATION_GROUP_RESTART(f64)       ,
    ANIMATION_GROUP_LISTEN(f64, EAnimationGroupListen)        ,
    ANIMATION_GROUP_ADD_FRAME_EVENT(f64, f64, f64),
    ANIMATION_GROUP_DELETE(f64)        ,
    QUERY_ANIMATION_GROUP_EVENTS()  ,
    QUERY_ANIMATION_CURVE()         ,
    CREATE_ANIMATION_CURVE(f64, EAnimePropertyID, Vec<f32>, EAnimeCurve)        ,
    PROPERTY_TARGET_ANIMATION(f64, EAnimePropertyID, f64, f64)     ,
    TRANSFORMNODE(f64, f64)                 ,
    TRANSFORMNODE_PARENT(f64, f64)          ,
    TRANSFORMNODE_POSITION(f64, f64, f64, f64)        ,
    TRANSFORMNODE_SCALING(f64, f64, f64, f64)         ,
    TRANSFORMNODE_EULER(f64, f64, f64, f64)           ,
    TRANSFORMNODE_ENABLE(f64, bool)          ,
    TRANSFORMNODE_QUATERNION(f64, f64, f64, f64, f64)      ,
    TRAIL(f64, f64, f64)                         ,
    TRAIL_AGE(f64, f64)                     ,
    CAMERA(f64, f64, Option<f64>)                        ,
    CAMERA_SIZE(f64, f64)                   ,
    CAMERA_FOV(f64, f64)                    ,
    CAMERA_ACTIVE(f64, bool)                 ,
    CAMERA_MODE(f64, bool)                   ,
    CAMERA_FIXED_MODE(f64, f64)             ,
    CAMERA_TARGET(f64, f64, f64, f64)                 ,
    CAMERA_NEARFAR(f64, f64, f64)                ,
    CAMERA_ASPECT(f64, Option<f64>)                 ,
    VIEWER_FORCEINCLUDE(f64, f64, bool)           ,
    CREATE_VERTEX_BUFFER(String, Vec<u8>)          ,
    CREATE_INDICE_BUFFER(String, Vec<u8>)          ,
    CREATE_INDICE_BUFFER32(String, Vec<u8>)        ,
    SPRITE(f64, Atom)                        ,
    SPRITE_FRAME(f64, Atom, f64)                  ,
    SPRITE_FRAME_DATA(f64, Atom, Vec<u16>)             ,
    SPRITE_FRAME_DATA_RECORD(SpriteFrame)      ,
    INSTANCE_MESH(f64, f64)                 ,
    INSTANCE_VEC4(f64, f64, f64, f64, f64, Atom)                 ,
    INSTANCE_VEC3(f64, f64, f64, f64, Atom)                 ,
    INSTANCE_VEC2(f64, f64, f64, Atom)                 ,
    INSTANCE_FLOAT(f64, f64, Atom)                ,
    INSTANCE_SINT(f64, f64, Atom)                 ,
    INSTANCE_UINT(f64, f64, Atom)                 ,
    INSTANCE_IVEC4(f64, f64, f64, f64, f64, Atom)                ,
    INSTANCE_U16X2(f64, f64, f64, Atom)                ,
    INSTANCE_U16X4(f64, f64, f64, f64, f64, Atom)                ,
    INSTANCE_U8X4(f64, f64, f64, f64, f64, Atom)                 ,
    MESH_BONE_OFFSET(f64, f64)              ,
    MESH_BONE_OFFSET_ARR(Vec<f64>)          ,
    MESH(f64, f64, VInstanceAttributes, bool)                          ,
    MESH_GEOMETRY(f64, GeometryMeta, Option<f64>)                 ,
    MESH_INDEXRANGE(f64, Option<f64>, Option<f64>)               ,
    MESH_MORPHTARGETINFLUENCE(f64, f64, f64, f64, f64)     ,
    MESH_VERTEXRANGE(f64, Option<f64>, Option<f64>)              ,
    MESH_BLEND(f64, bool, f64, f64, f64, f64, f64, f64, Option<f64>)                    ,
    MESH_CULLMODE(f64, f64, f64)                 ,
    MESH_FRONTFACE(f64, f64, f64)                ,
    MESH_TOPOLOGY(f64, f64, f64)                 ,
    MESH_POLYGON_MODE(f64, f64, f64)             ,
    MESH_CAST_SHADOW(f64, bool, f64)              ,
    MESH_RECEIVE_SHADOW(f64, bool, f64)           ,
    MESH_DEPTH_WRITE(f64, f64, f64)              ,
    MESH_DEPTH_COMPARE(f64, f64, f64)                  ,
    MESH_DEPTH_BIAS(f64, f64, f64, f64, f64)                     ,
    MESH_STENCIL_FRONT(f64, f64, f64, f64, f64, f64)            ,
    MESH_STENCIL_BACK(f64, f64, f64, f64, f64, f64)             ,
    MESH_STENCIL_WRITE(f64, f64, f64)            ,
    MESH_STENCIL_READ(f64, f64, f64)             ,
    MESH_BOUNDING_BOX(f64, f64, f64, f64, f64, f64, f64)             ,
    MESH_BOUNDING_CULLINGMODE(f64, f64)     ,
    MESH_RENDER_QUEUE(f64, f64, f64)             ,
    MESH_RENDER_QUEUE_ARR(Vec<f64>)         ,
    MESH_RENDER_ALIGNMENT(f64, f64)         ,
    MESH_INSTANCE_SORT_MODE(f64, f64)       ,
    MESH_SCALING_MODE(f64, f64)             ,
    MESH_VELOCITY(f64, f64, f64, f64)                 ,
    MESH_VELOCITY_ARR(Vec<f64>)             ,
    MESH_ATTRIBUTE_TARGET_ANIM(f64, f64, Atom, f64)    ,
    MESH_POSE_MATRIX(f64, Vec<f32>)              ,
    LIGHT(f64, f64, f64)                         ,
    LIGHT_DIRECTION(f64, f64, f64, f64)               ,
    LIGHT_STRENGTH(f64, f64)                ,
    LIGHT_SPOT_ANGLE(f64, f64, f64)              ,
    LIGHT_RADIUS(f64, f64)                  ,
    LIGHT_COLOR(f64, f64, f64, f64)                   ,
    MESH_FORCE_POINT_LIGHT(f64, f64, bool)        ,
    MESH_FORCE_SPOT_LIGHT(f64, f64, bool)         ,
    MESH_FORCE_HEMI_LIGHT(f64, f64, bool)         ,
    MATERIAL(f64)                      ,
    MATERIAL_SHADER(f64, Atom, bool)               ,
    MATERIAL_APPLY(f64, f64, f64)                ,
    MATERIAL_UNIFORM_MAT4(f64, Atom, [f32;16])         ,
    MATERIAL_UNIFORM_VEC2(f64, Atom, [f32;2])         ,
    MATERIAL_UNIFORM_VEC4(f64, Atom, [f32;4])         ,
    MATERIAL_UNIFORM_FLOAT(f64, Atom, f32)        ,
    MATERIAL_UNIFORM_UINT(f64, Atom, u32)         ,
    MATERIAL_UNIFORM_TEX(f64, Atom, Atom, bool, bool, bool, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64)          ,
    LOAD_TEXTURE(Atom, bool, bool, bool)                  ,
    MATERIAL_TEX_FROM_RENDERTARGET(f64, Atom, Atom, f64, bool, f64, f64, f64, f64, f64, f64, f64, f64, Option<f64>),
    MATERIAL_TEX_FROM_RENDERER(f64, Atom, Atom, f64, bool, f64, f64, f64, f64, f64, f64, f64, f64, Option<f64>)    ,
    MATERIAL_TARGET_ANIMATION(f64, f64, Atom, f64)     ,
    NODE_MATERIAL_BLOCK_REGIST(NodeMaterialBlock)    ,
    MATERIAL_REGIST(String, MaterialUniformDefines, String, String, String, String, NodematerialIncludes, String, P3DShaderVaryings, Option<f64>)               ,
    PARTICLESYS(f64, f64, f64, f64, Atom, Atom, Atom, Option<f64>)                   ,
    PARTICLESYS_WITH_GLTF(f64, f64, f64, f64, u64, f64, Atom, Atom, Option<f64>)         ,
    PARTICLESYS_START(f64)             ,
    PARTICLESYS_TIMESCALE(f64, f64)         ,
    PARTICLESYS_STOP(f64)              ,
    RENDER_SUBGRAPH(String)               ,
    RENDER(f64, String, f64, bool, Option<bool>, Option<bool>)                        ,
    RENDER_ENABLE(f64, bool)                 ,
    RENDER_CLEAR_LINK_MESH()        ,
    RENDER_TARGET_KEY(f64, Option<f64>, Option<bool>, Option<bool>)             ,
    RENDER_TARGET_AUTO(f64, f64, f64, f64, f64, Option<bool>)            ,
    RENDER_AUTO_CLEAR_COLOR(f64, bool)       ,
    RENDER_AUTO_CLEAR_DEPTH(f64, bool)       ,
    RENDER_AUTO_CLEAR_STENCIL(f64, bool)     ,
    RENDER_CLEAR_COLOR(f64, f64, f64, f64, f64)            ,
    RENDER_CLEAR_DEPTH(f64, f64)            ,
    RENDER_CLEAR_STENCIL(f64, f64)          ,
    RENDER_VIEWPORT(f64, f64, f64, f64, f64, Option<f64>, Option<f64>)               ,
    RENDER_LINK_DRAWLIST(f64, Vec<f64>)          ,
    RENDER_SCREEN_WITH_POSTPROCESS(bool),
    SHADOW_GENERATOR(f64, f64, f64, Option<f64>)              ,
    SHADOW_BASE_PARAM(f64, f64, f64, f64)             ,
    SHADOW_FRUSTUM(f64, f64, f64, f64)                ,
    SKELETON(f64, f64, Vec<f64>, f64, f64)                      ,
    BONE(f64)                          ,
    BONE_LINK(f64, f64)                     ,
    BONE_POSE(f64, [f32;16])                     ,
    SKIN_USE(f64, f64)                      ,
}
