[package]
name = "pi_export_base"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2021"

[features]
default = ["pi_js_export", "wasm_bindgen"]
pi_js_export = []
wasm_bindgen = []

[dependencies]
paste = "1.0"
pi_atom = "0.2"
derive_deref = "1.1"
pi_export_macro = {path="../macro"}
pi_share = {version="0.4"}
pi_assets = "0.11"
pi_hal={git="https://github.com/GaiaWorld/pi_hal.git"}
bevy = { version="0.10", default-features = false }
wgpu = { version = "0.15", default-features = false, feature = ["glsl"] }
pi_bevy_asset = { git = "https://github.com/GaiaWorld/pi_render_bevy.git" }
pi_bevy_render_plugin = { git = "https://github.com/GaiaWorld/pi_render_bevy.git" }
pi_bevy_ecs_extend = { git = "https://github.com/GaiaWorld/pi_render_bevy.git" }
pi_bevy_winit_window = { git = "https://github.com/GaiaWorld/pi_render_bevy.git"}
pi_bevy_post_process= { git = "https://github.com/GaiaWorld/pi_render_bevy.git"}
pi_window_renderer = { git = "https://github.com/GaiaWorld/pi_render_bevy.git" }
pi_render = { git = "https://github.com/GaiaWorld/pi_render.git", branch="bevy_shader" }
pi_async = {version = "0.5"}

js-sys = "0.3"
web-sys = {version="0.3", features = [
	"HtmlCanvasElement"
]}
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
pi_async = {version = "0.5", features = ["serial"]}
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]}
js-sys = "0.3"

