[package]
name = "pi_export_base"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2021"

[features]
default = ["pi_js_export", "wasm_bindgen"]
pi_js_export = []
wasm_bindgen = []

[dependencies]
paste = "1.0"
pi_atom = "0.2"
derive_deref = "1.1"
pi_export_macro = {path="../macro"}
pi_share = {version="0.4"}
pi_assets = "0.13"
pi_hal = {version = "0.1", registry = "yn"}
bevy = { version="0.11", default-features = false }
wgpu = { version = "0.16", default-features = false, feature = ["glsl"] }
pi_bevy_asset = {version = "0.1", registry = "yn"}
pi_bevy_render_plugin = {version = "0.1", registry = "yn"}
pi_bevy_ecs_extend = {version = "0.1", registry = "yn"}
pi_bevy_winit_window = {version = "0.1", registry = "yn"}
pi_bevy_post_process= {version = "0.1", registry = "yn"}
pi_window_renderer = {version = "0.1", registry = "yn"}
pi_bevy_log = {version = "0.1", registry = "yn"}
pi_render = {version = "0.1", registry = "yn"}
pi-async-rt = {version = "0.1"}
js_proxy_gen_macro = { registry = "yn", version = "0.2" }
tracing-subscriber = "0.3"

js-sys = "0.3"
web-sys = {version="0.3", features = [
	"HtmlCanvasElement"
]}
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]}
js-sys = "0.3"

