[package]
name = "pi_export_quad_tree"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2021"

[features]
default = ["pi_js_export"]
pi_js_export = []


[dependencies]
nalgebra = "0.32.0"
parry2d = "0.13"
bytemuck = { version = "1.4", features = ["derive"] }
pi_spatial = "0.6"
pi_slotmap = "0.2"
# a星相关模块
pi_path_finding = "0.6"
pi_orca = "0.5"
js_proxy_gen_macro = { registry = "yn", version = "0.2" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]}
